name: 🧪 Test for podman

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  podman-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install requirements
        run: sudo env PATH=$PATH just ci-prepare

      - name: Build youki
        run: just youki-release

      - name: Install vagrant and virtualbox
        run: |
          sudo apt-get update && sudo apt-get install virtualbox
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vagrant

      - name: Cache Vagrant boxes
        uses: actions/cache@v4
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile.podmane2e') }}
      
      - name: Cache virtualbox machine
        uses: actions/cache@v4
        with:
          path: "~/VirtualBox VMs"
          key: ${{ runner.os }}-virtualbox-${{ hashFiles('Vagrantfile.podmane2e') }}


      - name: Add the fedora box
        continue-on-error: true
        run: vagrant box add fedora/38-cloud-base --provider virtualbox

      - name: Boot vagrantbox
        run: VAGRANT_VAGRANTFILE=Vagrantfile.podmane2e vagrant up
      
      # run tests
      - name: Run podman tests
        run: VAGRANT_VAGRANTFILE=Vagrantfile.podmane2e vagrant up --provision-with test | tee build.log


      - name: Shut down vagrant box
        run: vagrant suspend

      - name: Adding Summary
        run: |
          echo "Total tests: 600+ Failed tests: $(cat build.log | grep "not ok " | wc -l)" >> $GITHUB_STEP_SUMMARY
