name: 🧪 Test for podman

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  podman-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install requirements
        run: sudo env PATH=$PATH just ci-prepare
      
      - name: Install skopeo and podman requirements
        run: |
          sudo apt-get install -y pkg-config libsystemd-dev libelf-dev libseccomp-dev libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev bats socat protobuf-compiler jq conmon containernetworking-plugins netcat apache2-utils wget
          wget http://ftp.debian.org/debian/pool/main/n/netavark/netavark_1.4.0-3_amd64.deb
          wget http://ftp.debian.org/debian/pool/main/a/aardvark-dns/aardvark-dns_1.4.0-3_amd64.deb
          wget http://ftp.debian.org/debian/pool/main/g/golang-github-containers-common/golang-github-containers-common_0.57.4+ds1-4_all.deb
          wget http://ftp.debian.org/debian/pool/main/s/skopeo/skopeo_1.13.3+ds1-2_amd64.deb
          sudo apt install ./netavark_1.4.0-3_amd64.deb ./aardvark-dns_1.4.0-3_amd64.deb ./golang-github-containers-common_0.57.4+ds1-4_all.deb ./skopeo_1.13.3+ds1-2_amd64.deb
          sudo npm install -g bats
      
      # setup go
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false

      # build youki
      - run: just youki-release
      - run: sudo rm /usr/bin/crun && sudo cp youki /usr/local/bin && sudo cp youki /usr/bin/crun

      # build podman
      - name: Clone podman repository
        uses: actions/checkout@v3
        with:
          repository: containers/podman
      - name: Build podman
        run: make binaries 
      - name: Install tools
        run: make install.tools
      
      # run tests
      - name: Run podman test
        run: |
          export BATS_TEST_TMPDIR=$(mktemp -d --tmpdir=${BATS_TMPDIR:-/tmp} podman_bats.XXXXXX)
          export PODMAN_TMPDIR=$BATS_TEST_TMPDIR 
          export OCI_RUNTIME=/usr/local/bin/youki 
          sudo make localsystem 2>&1 | tee build.log 

      - name: Adding Summary
        run: |
          echo "Total tests: 600+ Failed tests: $(cat build.log | grep " ok " | wc -l)" >> $GITHUB_STEP_SUMMARY
